defaults:
  - umi_lazy_dataset
  - _self_

_target_: diffusion_policy.dataset.umi_multi_dataset.UmiMultiDataset

dataset_root_dir: ???
used_episode_indices_file: ""

dataset_configs:
  cup_arrangement_0:
    include_episode_num: 500
  towel_folding_0:
    include_episode_num: 500
  mouse_arrangement_0:
    include_episode_num: 500

zarr_path: "" # Will be overridden in the initialization function
  
# The rest should be inherited from umi_lazy_dataset that are kept the same for all the datasets.